# Generated by Django 2.2.1 on 2019-05-31 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LimboMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=100)),
                ('given_names', models.CharField(max_length=64)),
                ('preferred_name', models.CharField(default='', max_length=32)),
                ('street_address', models.CharField(max_length=64)),
                ('postal_code', models.CharField(max_length=64)),
                ('city', models.CharField(max_length=64)),
                ('phone', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=64)),
                ('birth_date', models.DateField()),
                ('student_id', models.CharField(max_length=10)),
                ('degree_programme', models.CharField(max_length=256)),
                ('enrolment_year', models.IntegerField()),
                ('motivation', models.TextField(default='', max_length=2048)),
                ('subscribed_to_modulen', models.BooleanField(default=False)),
                ('allow_publish_info', models.BooleanField(default=False)),
            ],
        ),
    ]
