# Generated by Django 2.2.1 on 2019-06-09 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_auto_20190608_0025'),
    ]

    operations = [
        migrations.AddField(
            model_name='limbomember',
            name='mother_tongue',
            field=models.CharField(default='', max_length=64),
        ),
    ]
