# Generated by Django 2.2.1 on 2019-06-10 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_limbomember_mother_tongue'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LimboMember',
            new_name='Applicant',
        ),
    ]
