# Generated by Django 2.2.1 on 2019-06-15 15:07

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_auto_20190610_2250'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='country',
            field=django_countries.fields.CountryField(blank=True, default='FI', max_length=2),
        ),
    ]
