# Generated by Django 2.2.1 on 2019-08-26 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_applicant_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='allow_studentbladet',
            field=models.BooleanField(default=False),
        ),
    ]
