# Generated by Django 3.1.14 on 2023-04-24 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0008_auto_20230409_2329'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='username',
            field=models.CharField(max_length=16, null=True),
        ),
    ]
