# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-03-21 07:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0013_auto_20170928_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='preferred_name',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
