# Generated by Django 2.1.2 on 2018-11-19 20:56

from django.db import migrations

def move_phone_numbers(apps, schema_editor):
    Member = apps.get_model('members', 'Member')

    for member in Member.objects.all():
        if member.mobile_phone:
            member.phone = member.mobile_phone
            member.save()

class Migration(migrations.Migration):

    dependencies = [
        ('members', '0014_auto_20180321_0916'),
    ]

    operations = [
        migrations.RunPython(move_phone_numbers),
    ]
