# Generated by Django 2.1.3 on 2018-11-26 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0015_auto_20181119_2256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='crm_id',
        ),
        migrations.RemoveField(
            model_name='member',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='member',
            name='maiden_name',
        ),
        migrations.RemoveField(
            model_name='member',
            name='mobile_phone',
        ),
        migrations.RemoveField(
            model_name='member',
            name='nationality',
        ),
        migrations.RemoveField(
            model_name='member',
            name='nickname',
        ),
        migrations.RemoveField(
            model_name='member',
            name='url',
        ),
    ]
