# Generated by Django 2.2.1 on 2019-08-26 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0016_auto_20181126_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='allow_studentbladet',
            field=models.BooleanField(default=False),
        ),
    ]
