# Generated by Django 3.1.14 on 2023-04-20 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0018_auto_20230409_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decorationownership',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decoration_ownerships', to='members.member'),
        ),
        migrations.AlterField(
            model_name='functionary',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='functionaries', to='members.member'),
        ),
        migrations.AlterField(
            model_name='groupmembership',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_memberships', to='members.member'),
        ),
        migrations.AlterField(
            model_name='membertype',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_types', to='members.member'),
        ),
    ]
